### ISSUE TITLE
[Bug] SPB Crashes Sketch on Launch 

### ISSUE THREAD

**Issue by luxlogica** [mludowise/Sketch-Plugin-Manager#15]
After upgrading Sketch Plugin Manager (SPM) to the latest version, I could no longer launch Sketch - it would crash immediately on launch, with a crash report window.

If I go into the Sketch plugin folder, and manually start removing plugins, nothing seems to happen - it keeps crashing. However, when I remove the 'Fluid' or the 'Auto-Layout' plugin (either one), Sketch finally does launch successfully. But then, SPM's 'Update Plugins' alert comes up, and keeps coming back up, again, and again, and again, every few seconds after I dismiss it. 

Removing SPM allows Sketch to launch, and all plugins operate as usual.

**Comment by mludowise** [comment]
Thank you for bringing this to my attention. I believe I am able to reproduce the issue. I've reverted my changes which should hopefully fix it for now.

**Comment by mludowise** [comment]
Could you please attach your crash report so I can confirm the crash is being caused by what I think it is.

To retrieve the crash report:
  1. Open the folder **/Users/[your name]/Library/Logs/DiagnosticReports/**
  2. Locate a file .crash that starts with "Sketch_" that matches the timestamp you encountered the crash, it should be named something like **Sketch_2017-05-07-194043_Mels-MacBook-Pro.crash**

Thank you.

**Comment by luxlogica** [comment]
Here 'tis - I hope it helps!

[crash_report.zip](https://github.com/mludowise/Sketch-Plugin-Manager/files/982690/crash_report.zip)

**Comment by mludowise** [comment]
Thank you for the crash report. It looks like it's something different from what I thought it was.

I'm unable to reproduce the crash on my system but I believe I was able to fix the bug causing it. If you have the time, I would appreciate your help in testing the fix. I have a potential fix on the branch [crash-fix](https://github.com/mludowise/Sketch-Plugin-Manager/tree/crash-fix). 

In order to test:
1. Download the [Zipped archive from the crash-fix branch](https://github.com/mludowise/Sketch-Plugin-Manager/archive/crash-fix.zip) and unzip it into ~/Library/Application Support/com.bohemiancoding.sketch3/Plugins/. _Do not double-click on the .sketchplugin file to install because it may Sketch to crash immediately after install when the plugin directory structure changes._
2. Restart Sketch

To switch back to the production version of the plugin, you can uninstall and reinstall it from the catalog and restart Sketch.

Thank you.

**Comment by luxlogica** [comment]
The 'crash-fix' indeed fixes the crashing. As a bonus, it also seems to fix the screen redraw glitch reported in #13! ;-)

**Comment by mludowise** [comment]
Awesome! Thank you for your help testing the fix. I'll release an update later today and close out this issue after it's released.

**Comment by mludowise** [comment]
Fixed.
