### ISSUE TITLE
anima app

### ISSUE THREAD

**Issue by n8mills** [mludowise/Sketch-Plugin-Manager#23]
### Description

keeps asking me to update launchpad by anima > its up to date

### OS X Version

[//]: # (e.g. 10.12.4; To find the version number, go to the Apple menu -> About This Mac.)

### Sketch Plugin Manager Version

[//]: # (To find the version number, in Sketch go to Preferences > Plugins and look for the gray number next to "Sketch Plugin Manager".)

### Screenshot

[//]: # (Include a screenshot or screen recording, if applicable)

### Logs

[//]: # (Attach a .txt file containing logs for Sketch Plugin Manager. For instructions on how to export logs:)
[//]: # (For v1.4+: https://github.com/mludowise/Sketch-Plugin-Manager/wiki/Exporting-Logs-v1.4-or-higher)
[//]: # (For v1.3 or lower: https://github.com/mludowise/Sketch-Plugin-Manager/wiki/Exporting-Logs---v1.3-or-lower)

**Comment by mludowise** [comment]
How do you know that Anima is up to date? Did you update to the latest version using Anima's updater (`Launchpad by Anima > Version > Check For Update`) or did you update to the latest version in Sketch Plugin Manager and are still seeing a warning?

![image](https://user-images.githubusercontent.com/1626168/27112101-93139d82-5069-11e7-8a72-fe6be9201a98.png)

If you're using Anima's updater, it's likely that it conflicts with Sketch Plugin Manager because SPM uses Git to update and Anima uses another method. I don't have a fix for this immediately but Sketch is changing the way plugins do updates in v45, so I will be releasing updates for that which should fix this.

**Comment by mludowise** [comment]
FYI - I put in a fix in #30 for this which flags the Launchpad plugin as one that shouldn't be updated in Sketch Plugin Manager. It should display a message that says "Updates managed by Auto Layout" in the plugin manager and no longer prompt you to update in Sketch Plugin Manager.

![image](https://user-images.githubusercontent.com/1626168/27405886-1aeeaaf2-5688-11e7-98ba-b59747079546.png)
