### ISSUE TITLE
Sketch-Plugin-Manage can't use proxy.

### ISSUE THREAD

**Issue by vvhh2002** [mludowise/Sketch-Plugin-Manager#35]
### Description
Sketch-Plugin-Manage can't use proxy to download the plug-ins.

 BTW:where are source code of Sketch-Plugin-Manager.app of the bundle? I wish i could modify and submit a pull requests.

### OS X Version

[//]: # 10.12.6

### Sketch Plugin Manager Version

[//]: # 1.6

**Comment by mludowise** [comment]
Sorry I didn't get back to you sooner, it's been a while since I've been able to give this project my attention.

I don't believe there's anything that can be done to allow this to use a proxy. I'm using the Objective-Git library and I don't believe they have an option for that, but I could be wrong.

The Swift source code is in another repo that is private, but there's no reason why I couldn't open it up. The code is a bit messy as I was still learning some things when I wrote it, so you can look at it at your own risk :-) I'll try to open it up later this week after I fix some bugs and will let you know when that happens.
